default_context:
  project_name: 'blacklist'
  project_slug: 'blacklist'
  domain_main: 'blacklist.com'
  domain_staging: 'stag.blacklist.com'
  domain_base_api_url: 'http://blacklist.com/api/v1'
  domain_base_ws_url: 'ws://blacklist.com/api/v1'
  docker_swarm_stack_name_main: 'blacklist-com'
  docker_swarm_stack_name_staging: 'stag-blacklist-com'
  secret_key: '9f5c4b31f17fd65a9bae6235db64b9444cea723f2b77669b95f4a0eb56f04251'
  first_superuser: 'admin@blacklist.com'
  first_superuser_password: '123123123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.blacklist.com", "https://stag.blacklist.com", "https://blacklist.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@blacklist.com'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@blacklist.com'
  postgres_password: '23797ce0920fb3750ab596c2054110d723d59223fb738cea22d87896c09aa9af'
  pgadmin_default_user: 'admin@blacklist.com'
  pgadmin_default_user_password: 'e96b6cbd6e8722969846a8b3d865ad52910479ad097306884f4d869f8c00a42f'
  neo4j_password: '1e08a7f25a88145c6407194b96dc1fb8dba93d6cfa20c76c67d60591f7dfceed'
  traefik_constraint_tag: 'blacklist.com'
  traefik_constraint_tag_staging: 'stag.blacklist.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123123123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
